# Don't print a new line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
error_symbol = "[âœ˜ â¯](bold red)" 
success_symbol = "[âœ” â¯](bold green)" 
vicmd_symbol = "[v â¯](bold blue)"   
 
[package]
disabled = true

[directory]
read_only = " ğŸ”’"
truncation_length = 5
style = "bold dimmed cyan"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
progress_divider = " of "

[git_status]
conflicted = " ğŸ³ "
ahead = "ïƒ®Ã—  "
behind = "ïƒ­   "
diverged = "ï½  "
untracked = "ï™  "
stashed = " ğŸ“¦  "
modified = "ğŸ“  "
staged = "ğŸ—ƒï¸   "
renamed = "ğŸ‘…  "
deleted = "ğŸ—‘ï¸  "
format = "$all_status$ahead_behind"
